# Generated by Django 3.1.7 on 2021-03-20 16:41

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_useraccount_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('operation_type', models.CharField(choices=[('deposit', 'Deposit'), ('transfer', 'Transfer')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('account', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='common.useraccount')),
            ],
        ),
        migrations.AddConstraint(
            model_name='accountoperation',
            constraint=models.CheckConstraint(check=models.Q(amount__gte=Decimal('0')), name='amount_gte_0'),
        ),
        migrations.AlterIndexTogether(
            name='accountoperation',
            index_together={('account', 'created')},
        ),
    ]
