# Generated by Django 3.1.7 on 2021-03-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20210320_1641'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='accountoperation',
            name='amount_gte_0',
        ),
        migrations.AlterField(
            model_name='accountoperation',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
