# Generated by Django 3.1.7 on 2021-03-21 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20210321_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountoperation',
            name='account',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='common.useraccount'),
        ),
    ]
